name: Upload Airflow DAGs to S3
on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  upload_dags:
    name: Upload Airflow DAGs to S3
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Upload DAF file to S3 bucket
        uses: zdurham/s3-upload-github-action@master
        with:
          args: --acl public-read
        env:
          FILE: dags/batch_job.py
          AWS_REGION: ${{ secrets.AWS_REGION_NAME }}
          S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          S3_KEY: airflow_ana.py
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
