name: Build and push Docker image to ECR
on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  push_to_registry:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Login to AWS ECR
        id: ecr
        uses: jwalton/gh-ecr-login@v1
        env:
          AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          access-key-id: $AWS_ACCESS_KEY_ID
          secret-access-key: $AWS_SECRET_ACCESS_KEY
          region: $AWS_REGION_NAME

      - name: Push Docker Image to ECR
        env:
          IMAGE_TAG: ${{ github.sha }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
          REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
        run: |
          docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION_NAME.amazonaws.com/$REPOSITORY_NAME:$IMAGE_TAG .
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION_NAME.amazonaws.com/$REPOSITORY_NAME:$IMAGE_TAG
