name: Build and push Docker image to ECR
on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]

env:
  AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  push_to_registry:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - run: docker build --tag capstone-ana:v1.0.0 .

      - name: Login to Amazon ECR and push Docker image
        uses: jwalton/gh-ecr-push@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION_NAME }}
          image: capstone-ana:v1.0.0
